### ISSUE TITLE
npm test constructor error build failure

### ISSUE THREAD

**Issue by DennisM330** [sstone1/blockchain-starter-kit#5]
I am getting a build failure in the toolchain. Below is a section of the logs showing the failure. I suspect this may be due to needing the most current generator?

+ npm test

> dennis-network@0.0.1 test /home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network
> mocha --recursive

/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/test/logic.js:21
    const cardStore = new MemoryCardStore();
                      ^

TypeError: MemoryCardStore is not a constructor
    at Suite.describe (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/test/logic.js:21:23)
    at Object.create (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at Object.<anonymous> (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/test/logic.js:19:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/node_modules/mocha/lib/mocha.js:253:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/node_modules/mocha/lib/mocha.js:250:14)
    at Mocha.run (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/node_modules/mocha/lib/mocha.js:577:10)
    at Object.<anonymous> (/home/pipeline/c9dc9d8e-1dfc-4d10-8c67-436610fb8200/contracts/dennis-network/node_modules/mocha/bin/_mocha:591:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! Test failed.  See above for more details.

Finished: FAILED

**Comment by sstone1** [comment]
@DennisM330 yeah, you need to use the generators from Composer v0.19.x. There's been various improvements to the business network and Angular generator that enable starter kit to work.

Note that the BNA gets deployed with Composer v0.18.1 (as starter plan currently uses the RC version of Fabric v1.1), but BNAs built with v0.19.x are still compatible with this version.
