### ISSUE TITLE
Deploy fails 

### ISSUE THREAD

**Issue by sjanakir2015** [sstone1/blockchain-starter-kit#7]
1.  Under Step "4. Creating a smart contract":  
Under "Using composer",
Please consider adding the command to create a .bna file
 `composer archive create -t dir -n . `

2.  In Deploy, the .bna file is expected to be in "dist" folder  (example:  dist/sjnetwork@0.0.1.bna)
consider adding a command to this effect: 
`composer archive create --archiveFile ./dist/<contract-name> -t dir -n .`

3.  After adding the .bna file to "dist" folder, the Deploy stage fails with the same error as described in [hyperledger/composer#3944](https://github.com/hyperledger/composer/issues/3944).
From log of "Stage History / Deploy": 

/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();			                                                    
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308:56)
...
...
failed to install composer contract sjnetwork
+ echo failed to install composer contract sjnetwork
+ exit 1

Finished: FAILED

**Comment by simonmullaney** [comment]
Same issue

**Comment by simonmullaney** [comment]
Found a way around it:

add:
```
 npm install grpc@1.9.1
```
before the line:
```
    for BUSINESS_NETWORK_ARCHIVE in ${BUSINESS_NETWORK_ARCHIVES}
``` 

in the file -> pipeline-DEPLOY.sh , in function deploy_composer_contract

**Comment by sjanakir2015** [comment]
The issue is not fixed.  

Log from Deploy stage: 
> grpc@1.9.1 install /home/pipeline/e3d3b216-b485-4c52-a61b-a678139ef109/contracts/sjnetwork/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/home/pipeline/e3d3b216-b485-4c52-a61b-a678139ef109/contracts/sjnetwork/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" is installed via remote

> protobufjs@6.6.3 postinstall /home/pipeline/e3d3b216-b485-4c52-a61b-a678139ef109/contracts/sjnetwork/node_modules/protobufjs
> node scripts/postinstall

npm WARN sjnetwork@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ grpc@1.9.1
added 754 packages in 36.187s
+ for BUSINESS_NETWORK_ARCHIVE in '${BUSINESS_NETWORK_ARCHIVES}'
++ composer runtime install -c admin@blockchain-network -n sjnetwork
failed to install composer contract sjnetwork
+ OUTPUT='
Writing Node.js report to file: node-report.20180504.133953.2677.001.txt
Node.js report completed
/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                    ^

TypeError: Cannot read property '\''getConnectivityState'\'' of undefined
    at ClientDuplexStream.<anonymous> (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:629:19)
    at /home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:728:14'
+ [[ 
Writing Node.js report to file: node-report.20180504.133953.2677.001.txt
Node.js report completed
/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:629:19)
    at /home/pipeline/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:728:14 != *\a\l\r\e\a\d\y\ \i\n\s\t\a\l\l\e\d* ]]
+ echo failed to install composer contract sjnetwork
+ exit 1

Finished: FAILED

**Comment by sjanakir2015** [comment]
Deploys successfully !

I removed what I had added earlier, namely,
 "npm install grpc@1.9.1" 
Please refer to comments earlier here.
